### ISSUE TITLE
Assigning Unique ID to same person

### ISSUE THREAD

**Issue by sanchitjain04** [ambakick/Person-Detection-and-Tracking#12]
Hi, I wanted to as like is it possible to assign a unique ID to a person, also the id remains the same when that same person is out of frame and comes back rather assigning different tracking id?

Thank you

**Comment by ajaysg-zz** [comment]
hi i am also working on the same thing. i think it is not possible in real time, but u can do that for videos. u need to use person-reid module to reidentify a person when he is out of frame and entering again. Please refer to this 
https://github.com/Nirvan101/Person-Re-identification. If u find a better implementation pls let me know

**Comment by sanchitjain04** [comment]
@ajaysg  Thank you! sure i will update here if found something better!
