### ISSUE TITLE
how about comparison with yolov3?

### ISSUE THREAD

**Issue by chunniunai220ml** [ambakick/Person-Detection-and-Tracking#2]
Hi,
you said that SSD achieves 75.1% mAP, outperforming a comparable state of the art Faster R-CNN model. how about comparison with yolov3 on time and accuracy? 

and how can use your ssd-inception-v2.pb to detect my custom videos?

**Comment by ambakick** [comment]
![image](https://user-images.githubusercontent.com/24716987/50514436-34f74980-0ac4-11e9-9e0a-749f89c81755.png)
SRC: SSD Paper Arxiv

This is the case of Yolo v1. I haven't done a comparison or studies with YOLO v3. It has a significant improvement in performance according to my knowledge.

Close the issue if resolved!

**Comment by samannikzad** [comment]
Hi, Thank you for the brilliant work. My question is how can i extend tracking frames, for example detect only in every 5 frames instead of every frame??
