### ISSUE TITLE
test on my own video

### ISSUE THREAD

**Issue by ibrahimacar** [ambakick/Person-Detection-and-Tracking#3]
How to test on my own video?

**Comment by ambakick** [comment]
The tweaking has to be done on the OpenCV side of the code. 

1. Go to the main function of the Person_det_track.py

2. Under "if __name__ == "__main__":  "
 cap = cv2.VideoCapture(0)
#this means that the video is streamed from the video camera by OpenCV

change it to 
cap = cv2.VideoCapture('trial.mp4')
#This will make OpenCV Stream from the local video file.
**NOTE**: Before doing this add "trial.mp4" to the same folder.

Hope this works for you.

**Comment by ambakick** [comment]
Please close the issue if your problem is resolved.

**Comment by ibrahimacar** [comment]
Thanks a lot
