### ISSUE TITLE
How to run and test it?

### ISSUE THREAD

**Issue by DuckStarBall** [ambakick/Person-Detection-and-Tracking#4]
Hi,first thanks very much.I want to try to run on my own video,but it didn't work,so what should I do to test on my video?Should i write a demo.py?

**Comment by ambakick** [comment]
Refer the answer at : [https://github.com/ambakick/Person-Detection-and-Tracking/issues/3]

**Comment by ambakick** [comment]
Please close the issue if your problem is resolved.

**Comment by DuckStarBall** [comment]
thanks.
